### ISSUE TITLE
unexpected keyword error 'redis_password'

### ISSUE THREAD

**Issue by faentari** [isofit/isofit#172]
I'm encountering an issue with running the Pasadena example in the README file. After installing isofit from PyPI (python 3.7.9) and installing LibRadTran, I ran 

```
 cd examples/20171108_Pasadena
./run_example_libradtran.sh
```

which produced the following error

```
$ ./run_example_libradtran.sh
Checking config sections for configuration issues
Configuration check: measured_radiance_file is not an object, skipping
...
Configuration file checks complete, no errors found.
Traceback (most recent call last):
  File "/Users/xxx/anaconda2/envs/isofit/bin/isofit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/xxx/isofit-current-release/bin/isofit", line 54, in <module>
    main()
  File "/Users/xxx/isofit-current-release/bin/isofit", line 47, in main
    isofit = Isofit(config_file=config, level=level, row_column=row_column)
  File "/Users/xxx/isofit-current-release/isofit/core/isofit.py", line 93, in __init__
    ray.init(**rayargs)
TypeError: init() got an unexpected keyword argument 'redis_password'
```
This error is solved by going into isofit/core/isofit.py and commenting out the following line in the initialization of rayargs

```
'redis_password': self.config.implementation.redis_password,
```

**Comment by pgbrodrick** [comment]
Hello, and thanks for the post.

This is a known open issue (see #164), that resulted from ray configuration changes during the migration from 0.8.5 to 1.0.  If you haven't pulled the latest version of the code, I suggest doing so - I recently updated the installation configuration to address this specifically.  The current (temporary) solution, is to require ray 0.8.5.  If you're using pip, a 
'''
pip install --upgrade ray==0.8.5
'''
should do the trick.  Longer term, I'll be updating the code to use ray 1.0.+, but I'm still having issues getting that to work in the multi-node environment at present.

Let me know if the above fixes the issue.

**Comment by faentari** [comment]
Installing ray 0.8.5 as noted above fixed the issue. Thanks!
