### ISSUE TITLE
pygrib dependency in HRRR_profiles

### ISSUE THREAD

**Issue by pgbrodrick** [isofit/isofit#191]
add_HRRR_profiles_to_modtran_config.py requires pygrib, which requires a conda install or an a prior install of ECODES (https://pypi.org/project/pygrib/).  Utils CI workflow should be updated to accommodate, and the utils install procedure expanded to include.

**Comment by jammont** [comment]
`pygrib` has been made an optional install for ISOFIT to be able to use this script. As it is a mostly unused script with no present tests for it, I'll be closing this issue for now. If this is still a desired capability, please open a new ticket.
