### ISSUE TITLE
SIGABRT received due to bad_alloc

### ISSUE THREAD

**Issue by quarkpt** [isofit/isofit#272]
During processing of Hyperion scenes with ISOFIT, the following exception and stack trace occurred:

Extracting /nobackupp10/hyperion/pipeline/results/task-data/44-62-level1/st-2236/input/EO1H0990612008294110P1_subs_loc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** SIGABRT received at time=1651191029 on cpu 23 ***
PC: @     0x2aaaab832387  (unknown)  raise
    @     0x2aaaaacde630  (unknown)  (unknown)
[2022-04-28 17:10:29,157 E 38592 42959] logging.cc:325: *** SIGABRT received at time=1651191029 on cpu 23 ***
[2022-04-28 17:10:29,157 E 38592 42959] logging.cc:325: PC: @     0x2aaaab832387  (unknown)  raise
[2022-04-28 17:10:29,157 E 38592 42959] logging.cc:325:     @     0x2aaaaacde630  (unknown)  (unknown)
/nobackupp15/ptenenba/git/sister/dist/bin/level1: line 16: 38592 Aborted                 (core dumped) $DIST_ROOT/env/hyperion/bin/level1 $DIST_ROOT/env/hyperion/lib/python3.8/site-packages/hyperion/level_1.py

We have seen this once out of just over 2,200 scenes processed.

**Comment by pgbrodrick** [comment]
I believe this is a system resource issue, not a ray or python issue.  As such, closing.
