### ISSUE TITLE
No error thrown when state parameter not used by RTM

### ISSUE THREAD

**Issue by reginaeckert** [isofit/isofit#316]
No error is thrown when statevector name is used that is not accepted by the radiative transfer model in use (i.e. using ‘AERFRAC_0’ when attempting to use sRTMnet / six_s, which only accepts ‘AOT550’).

Could potentially be checked when: 
1. building the Configs
2. LUT files are generated
3. pkl files are generated
4. Forward model is run

**Comment by jammont** [comment]
Current design in v3 allows RTEs to be agnostic to the statevector names on creation; however, for an existing LUT, the config must match whatever is in the LUT. Exceptions will be raised at different points of the RTE class if the lut_grid or subsetting strategy does not match the LUT, for instance. 

Closing as this does not appear to be relevant to v3 at this time.
