### ISSUE TITLE
April Fool Spectrum

### ISSUE THREAD

**Issue by davidraythompson** [isofit/isofit#361]
The EMIT Mauritania spectra from April 1 have an issue - overcorrection of H2O vapor, possibly due to an issue with the lookup table range?  Not sure why it's going wrong here. Plot courtesy Willow Coleman, JPL.
![image_720](https://user-images.githubusercontent.com/2358270/236027490-b5369ae9-2e24-4925-a480-1fd751811589.png)

**Comment by willowcoleman** [comment]
Note that this is actually in Niger, had an bug with E/W coordinates in the geojson
