### ISSUE TITLE
Move from Tensorflow to Pytorch

### ISSUE THREAD

**Issue by jammont** [isofit/isofit#401]
The Docker images have significant issues with while building with Tensorflow, but no issues with Pytorch. It would be ideal for ISOFIT to move towards dropping support for Tensorflow in favour of Pytorch.

At this time, this effort is stalled until the following:
- [ ] sRTMnet rebuilt and tested in Pytorch
- [ ] Alberto's research code converted to Pytorch

**Comment by pgbrodrick** [comment]
Just removed tensorflow with numpy.  Suggest Alberto's code should look to implement Pytorch as it becomes revived.
