### ISSUE TITLE
Remove custom FileExistsError()

### ISSUE THREAD

**Issue by pl-kevinwurster** [isofit/isofit#445]
Part of `isofit` defines its own `FileExistsError()`, however Python already offers this exception. I _think_ this is new in Python 3 though, so possibly this custom exception seeks to bridge the two language versions.

https://github.com/isofit/isofit/blob/5cf282b7a8f58c9b89e8d580ec0db54e9ae9ddc6/isofit/radiative_transfer/modtran.py#L48

It is worth noting that Python's subclasses `OSError()`, while `isofit`'s subclasses `Exception()`. Unclear if this matters, so I recommend waiting to do this until the CI system is functional again.

```console
$ python3 -c "print(FileExistsError.__bases__)"
(<class 'OSError'>,)
```

**Comment by pgbrodrick** [comment]
This class can now be fully removed (it's no longer used).
