### ISSUE TITLE
VectorInterpolator error

### ISSUE THREAD

**Issue by davidraythompson** [isofit/isofit#446]
Hi everyone, I'm running the dev_2x branch and get the following error.  Any ideas? 

 File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/drt/src/isofit/isofit/core/isofit.py", line 314, in _cli
    Isofit(config_file=config_file, level=level).run()
  File "/home/drt/src/isofit/isofit/core/isofit.py", line 179, in run
    res = list(
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/ray/util/actor_pool.py", line 161, in get_generator
    yield self.get_next_unordered()
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/ray/util/actor_pool.py", line 361, in get_next_unordered
    return ray.get(future)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/tmp/miniconda/envs/isofit_env/lib/python3.10/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::Worker.run_set_of_spectra() (pid=44727, ip=172.16.0.9, actor_id=d54e61da81f71ef68d90b1c201000000, repr=<isofit.core.isofit.Worker object at 0x7fea12dcc490>)
  File "/home/drt/src/isofit/isofit/core/isofit.py", line 256, in run_set_of_spectra
    states = self.iv.invert(input_data.meas, input_data.geom)
  File "/home/drt/src/isofit/isofit/inversion/inverse.py", line 340, in invert
    x0 = invert_simple(self.fm, meas, geom)
  File "/home/drt/src/isofit/isofit/inversion/inverse_simple.py", line 398, in invert_simple
    x[forward.idx_RT] = heuristic_atmosphere(
  File "/home/drt/src/isofit/isofit/inversion/inverse_simple.py", line 108, in heuristic_atmosphere
    rhi = RT.get_shared_rtm_quantities(x_RT_2, geom)
  File "/home/drt/src/isofit/isofit/radiative_transfer/radiative_transfer.py", line 132, in get_shared_rtm_quantities
    ret.append(RT.get(x_RT, geom))
  File "/home/drt/src/isofit/isofit/radiative_transfer/sRTMnet.py", line 337, in get
    return self._lookup_lut(point)
  File "/home/drt/src/isofit/isofit/radiative_transfer/sRTMnet.py", line 294, in _lookup_lut
    ret = {key: lut(point) for key, lut in self.luts.items()}
  File "/home/drt/src/isofit/isofit/radiative_transfer/sRTMnet.py", line 294, in <dictcomp>
    ret = {key: lut(point) for key, lut in self.luts.items()}
  File "/home/drt/src/isofit/isofit/core/common.py", line 264, in __call__
    return self._multilinear_grid(*args, **kwargs)
  File "/home/drt/src/isofit/isofit/core/common.py", line 203, in _multilinear_grid
    x = np.zeros((len(points) + np.sum(self.lut_interp_types != "n")))
AttributeError: 'VectorInterpolator' object has no attribute 'lut_interp_types'
srun: error: node009: task 0: Exited with exit code 1

**Comment by davidraythompson** [comment]
Here's my config file.

{
    "ISOFIT_base": "/home/drt/src/isofit",
    "forward_model": {
        "instrument": {
            "SNR": 500,
            "integrations": 100,
            "unknowns": {
                "uncorrelated_radiometric_uncertainty": 0.01
            },
            "wavelength_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/data/wavelengths.txt"
        },
        "radiative_transfer": {
            "lut_grid": {
                "AOT550": [
                    0.001,
                    0.1,
                    0.2
                ],
                "H2OSTR": [
                    1.1995,
                    1.448,
                    1.6966,
                    1.9452,
                    2.1937,
                    2.4423,
                    2.6908,
                    2.9394
                ],
                "RELAZ":[0,1],
                "OBSZEN":[179,180]
            },
            "radiative_transfer_engines": {
                "vswir": {
                    "wavelength_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/data/wavelengths.txt",
                    "aerosol_model_file": "/home/drt/src/isofit/data/aerosol_model.txt",
                    "aerosol_template_file": "/home/drt/src/isofit/data/aerosol_template.json",
                    "earth_sun_distance_file": "/home/drt/src/isofit/data/earth_sun_distance.txt",
                    "emulator_aux_file": "/beegfs/scratch/brodrick/emulator/sixs-modtran-emulator/hialt_reruns/tenth_mse_dense/emulator_random_aux.npz",
                    "emulator_file": "/beegfs/scratch/brodrick/emulator/sixs-modtran-emulator/hialt_reruns/tenth_mse_dense/emulator_random.h5",
                    "engine_base_dir": "/home/drt/src/6sv/",
                    "engine_name": "sRTMnet",
                    "interpolator_base_path": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/interpolator/",
                    "irradiance_file": "/home/drt/src/isofit/examples/20151026_SantaMonica/data/prism_optimized_irr.dat",
                    "lut_names": [
                        "AOT550",
                        "H2OSTR",
                        "OBSZEN",
                        "RELAZ"
                    ],
                    "lut_path": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/lut_full",
                    "statevector_names": [
                        "AOT550",
                        "H2OSTR"
                    ],
                    "template_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/config/prm20231113t134427_modtran.json"
                }
            },
            "statevector": {
                "AOT550": {
                    "bounds": [
                        0.001,
                        0.2
                    ],
                    "init": 0.1009,
                    "prior_mean": 0.1009,
                    "prior_sigma": 10.0,
                    "scale": 1
                },
                "H2OSTR": {
                    "bounds": [
                        1.1995,
                        2.9394
                    ],
                    "init": 2.1936999999999998,
                    "prior_mean": 2.1936999999999998,
                    "prior_sigma": 100.0,
                    "scale": 1
                }
            },
            "unknowns": {
                "H2O_ABSCO": 0.0
            }
        },
        "surface": {
            "select_on_init": true,
            "surface_category": "multicomponent_surface",
            "surface_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/data/surface.mat"
        }
    },
    "implementation": {
        "debug_mode": false,
        "inversion": {
            "windows": [
                [
                    350.0,
                    1360.0
                ],
                [
                    1410,
                    1800.0
                ],
                [
                    1970.0,
                    2500.0
                ]
            ]
        },
        "n_cores": 40,
        "ray_temp_dir": "/tmp/ray"
    },
    "input": {
        "reference_reflectance_file":"/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/insitu/site_0_rfl.txt",
        "measured_radiance_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/data/prm20231113t134427_site0_original_rdn.txt"
    },
    "output": {
        "estimated_reflectance_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/output/prm20231113t134427_site0_rfl.txt",
        "radiometry_correction_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/output/prm20231113t134427_site0_factors.txt",
        "estimated_state_file": "/beegfs/scratch/drt/20231126_PRISM_BioSCapeVicariousCal/output/prm20231113t134427_site0_state.txt"
    }
}

**Comment by pgbrodrick** [comment]
Marking as stale as we migrate fully to 3.0
