### ISSUE TITLE
Fix sRTMnet zenodo reference

### ISSUE THREAD

**Issue by pgbrodrick** [isofit/isofit#470]
https://github.com/isofit/isofit/blob/dev/scripts/download-and-unpack-sRTMnet.sh currently uses a reference to https://avng.jpl.nasa.gov/pub/PBrodrick/isofit/.  Fix this and associated documentation as soon as zenodo upload is complete.

**Comment by jammont** [comment]
Has the Zenodo upload been completed?

**Comment by pgbrodrick** [comment]
@jammont - now complete, see: https://zenodo.org/records/10831425.
