### ISSUE TITLE
Aerosol convergence for VNIR vs SWIR

### ISSUE THREAD

**Issue by saumit-kobold** [isofit/isofit#483]
When running inversions on a VNIR sensor with wavelengths from 400nm-1000nm, the retrieved AOT550 is very close to the initial value, which in this case is also the prior mean. The prior covariance is set to be very broad and the 6s engine was used in this case. In contrast, for a SWIR sensor with wavelengths from 900nm to 2500nm the retrieved aerosol value varies more, but converges to different values that depend on the prior. 

Would appreciate any guidance about why this might be the case and good values to use for parameters. Happy to provide any additional details that can help. Also including a plot that shows the initialized and retrieved aerosol and water vapor values for the VNIR sensor that demonstrates this issue

![image](https://github.com/isofit/isofit/assets/126520240/9dd4b044-026f-411e-bca2-f91d886694ed)

**Comment by pgbrodrick** [comment]
Hello there - it's difficult to say too much without additional detail on the setup; but I can give two general statements:

- As indicated above, the covariance strength and representation are very important here - if you use the sample priors, for example, a uniform reflectance is likely not well represented (as it's not common on the Earth surface).  You may also need to adjust the structure and regularization.  We're working on better tutorials for this, but in the mean time please see: https://github.com/davidraythompson/istutor/blob/master/14_OptimalEstimationD/14_OE_Constraints.ipynb (note that this was built with a previous version of isofit, so the precise calls may be out of date - though the general functionality is the same)
- SWIR wavelengths can be useful for retrieving AOD (particularly at high loadings, e.g. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021JD034905), but again a lot of this depends on the covariance matrix structure.  If using a block-diagonal structure, the influence of the SWIR-2 will likely be reduced - which is often useful, but depends on the nature of the problem you are trying to solve.

**Comment by pgbrodrick** [comment]
Closing as stale, please feel free to re-open.
