### ISSUE TITLE
use of project board

### ISSUE THREAD

**Issue by pgbrodrick** [isofit/isofit#51]
Hey All,

Anyone mind if I start a project board for organization of checked out issues?  Would be nice to be able to see what folks are working on / assign/be-assigned tasks to minimize redundant work.  Also would be good to post some of the roadmap items on there.

**Comment by winstonolson** [comment]
Sounds like a good idea to me, and a chance to revisit older issues that may have gone stale or become obsolete.  I say go for it!

**Comment by pgbrodrick** [comment]
Great - can you add me as a collaborator so I can build one?

**Comment by winstonolson** [comment]
I just realized I don't have access to the Settings on this repo.  @davidraythompson, can you add Phil as a collaborator when you have a chance?  Thanks!

**Comment by isofit** [comment]
Hi Winston, @davidraythompson is also a lowly collaborator without the ability to change settings.  But Behold! I, the omniscient entity ISOFIT, have now invited Phil to the official repo to wield the sacred push/pull access.

**Comment by pgbrodrick** [comment]
Thanks omiscient entity!  Will start up a some projects, feel free to edit at your leisure.
