### ISSUE TITLE
Need higher numba version in setup.py

### ISSUE THREAD

**Issue by jfahlen** [isofit/isofit#59]
Line 26 in isofit.py fails with an import error as a more recent version of numba is required than is listed in setup.py.

The line is: from numba.errors import NumbaWarning, NumbaDeprecationWarning, NumbaPendingDeprecationWarning

setup.py lists a numba version >= 0.38. I updated to the most recent version of numba (0.47) and the error went away. I'm not sure which is the earliest numba version to support that import statement.

**Comment by davidraythompson** [comment]
Solved in v2.0
