### ISSUE TITLE
Error in transup_interp

### ISSUE THREAD

**Issue by jfahlen** [isofit/isofit#60]
Lines 184-185 of look_up_tables.py incorrectly assigned transm to transup_interp. transup is only used for the thermal L_s radiance so this probably doesn't affect too many results, but any thing used the thermal radiance is a bit suspect.

Original:
`self.transup_interp = VectorInterpolatorJIT(
            self.lut_grids, self.transm)`
Fix:
`self.transup_interp = VectorInterpolatorJIT(
            self.lut_grids, self.transup)`

**Comment by davidraythompson** [comment]
This is fixed (thanks Jay!) so I'll close out the issue.
