### ISSUE TITLE
config parameter assignment to classes

### ISSUE THREAD

**Issue by pgbrodrick** [isofit/isofit#75]
Read in the config in one shot, check it for any issues (ie parameters that don't exist), and assign config parameters to classes ASAP.  If this means we need a config class, make one.  As is, a series of dictionaries/subdictionaries of configurations are passed around that are difficult to trace and never verified.  Should be done after/in conjunction with #74 .

**Comment by adam-erickson** [comment]
Feel free to view the HyperTrace code for an example of this, but I believe you have experience with this already. I would also instead consider PEP 589, which provides strongly typed dictionaries ([link](https://www.python.org/dev/peps/pep-0589/)). The types can be built-in or custom. As we discussed, one thing we have to be careful of is to not modify the parameters object as it passes through the processing pipeline. A `Parameters` class is only necessary when it requires member functions, iterators, generators, etc. This comes at the cost of added complexity. I still feel it would be ideal, if that functionality is not needed, to immediately unpack a strictly typed dictionary upon initialization. This way, there is some built-in validation and each parameter is visible and not hidden within a `Parameters` class instance, easily exportable to a JSON file. Dictionary unpacking is also super simple with `**kwargs` in Python, with each parameter subsequently passed though functions explicitly (not hidden within a class instance or `self`). This will make it much easier to follow the program logic. The only reason I used a parameters class in my case is that member functions and iterators were needed in that case. Again, I _strongly_ support the additional of parameter value validation in a new `validation` module, which we do as well. This will take away a lot of the mystery in debugging, as currently the parameter values are not checked at all and there is overuse of implicit calls to `self` that mutates an entire tree of complex object states. Adding yet another class could make this more onerous. In other words, my vote is for a simple, serializable, immutable parameters object and explicit passing of parameters to functions to ease debugging. Dictionaries are also faster than classes, though they may use slightly more memory. The new strictly typed dictionaries solve most of the aforementioned problems.
