### ISSUE TITLE
Profile option doesn't work

### ISSUE THREAD

**Issue by ashiklom** [isofit/isofit#79]
Currently, running with `isofit --profile` returns an invalid number of kwargs error. This is almost certainly because the profiler calls `invert(meas, geom, configs)`, but the `invert` method only takes the first two arguments.

I'll fix this in a forthcoming PR -- just making a note for myself here.

**Comment by pgbrodrick** [comment]
Thanks for catching this - I'll attach a fix to the #73 PR that's pending.

**Comment by pgbrodrick** [comment]
And fix is now attached, closing.  Thanks again.
